### ISSUE TITLE
Unexpected vol.transfer_to() behaviors

### ISSUE THREAD

**Issue by nkemnitz** [seung-lab/cloud-volume#156] opened 2018-11-28 18:23 UTC
While running `transfer_to` to copy a small cutout from a larger segmentation to the new destination, I noticed a few unexpected behaviors:
- The `Content-Type` of my compressed segmentation got changed from `image/x.compressed_segmentation` to `application/octet-stream`
- My new cutout info file got replaced with the old info file
- No downsampled layers were copied

The last two might be intended behavior, although it's not exactly what I expected, which is either
a) respect the target info file and try to copy `vol.bounds` to fit the target `info`, or
b) warn that the directory is not empty, and copy `vol.bounds` and `scales` according to the source info

**Comment by william-silversmith** [comment] 2018-11-28 18:54
- Good call on the content type.
- I've been mostly using transfer_to to make new layers, so I never had to consider this issue. It's time to fix it. 
- I don't think copying downsamples would be universally intended behavior since a cloudvolume instance has a particular mip level. It's also not entirely clear what this would entail exactly. If you specify a bounding box, the mip levels for that bounding box are only well defined so long as each successive mip is greater than 2x the chunk size. Above that point, surrounding regions will be pulled in.

I think (a) makes more sense as a common use case might be to cal `transfer_to` multiple times for different bounding boxes. It might make sense to check if the existing bounds match the source.

**Comment by william-silversmith** [comment] 2018-11-28 19:07
Actually, thinking about that a bit more, it makes more sense to respect the source file and abort if the layer infos don't match. The point of transfer_to is to avoid having to do memory intensive rechunking, so matching the source is mandatory.

**Comment by william-silversmith** [comment] 2018-11-29 00:31
Hopefully this should be fixed now. Please reopen if there are additional issues.

**Closed by william-silversmith** 2018-11-29 00:31 UTC
Labels: bug
