### ISSUE TITLE
Default options in graphene mesh download are not robust

### ISSUE THREAD

**Issue by ceesem** [seung-lab/cloud-volume#495] opened 2021-07-26 15:58 UTC
In trying to make examples using release data, I'm downloading the mesh for segment id 864691134988768122. However, using `cv.mesh.get(864691134988768122)` does not return the full mesh, instead there is at least one large chunk missing from it. After some poking around, it turns out to work with `cv.mesh.get(864691134988768122, use_bytes_offset=True)`. The reason that this is an option at all is, based on the docstring:

```
    The manifest for sharded is a bit strange in that exists(..., return_byte_offset=True)
    is being called on the server side. To avoid duplicative delay by recomputing the offset
    locations, the manifest breaks encapsulation by returning the shard filename and byte
    offsets. This breaks enapsulation of the shard fetching logic rather severely but 
    it is probably worth it.
```

However, in cases like this one, the work is clearly non-duplicative and an average user would have no idea how to set this option to work robustly. I feel like the default options should be tuned for maximal robustness, and a user interested in improving efficiency should need to opt-in for options that might not work.

**Comment by jefferis** [comment] 2021-07-26 18:21
As a follow-up to this:
1. I have never had to use this for FAFB-FlyWire
2. I have been having apparently related problems with FANC (thanks @bjm5164 for the tip)

I have been using [cv.mesh.save](https://github.com/seung-lab/cloud-volume/blob/1d97ed942e5b1b01f9fcf3bd8c214259d20d0c50/cloudvolume/datasource/precomputed/mesh/unsharded.py#L199) but it seems I will need to switch to [cv.mesh.get](https://github.com/seung-lab/cloud-volume/blob/1d97ed942e5b1b01f9fcf3bd8c214259d20d0c50/cloudvolume/datasource/precomputed/mesh/unsharded.py#L115) in order to set `use_bytes_offset=True`. Is this the case @william-silversmith? Or is there a way to set this as a default when creating the `CloudVolume` object?

**Comment by ceesem** [comment] 2021-07-26 18:21
As a related aside, I just realized that non-graphene `cv.mesh.get` does not have `use_bytes_offset` as a keyword parameter. This makes it extremely difficult to write code that works for an arbitrary cloud path when different mesh retrieval functions have different options that are required for basic functionality (I'm guessing that multi-LOD downloading has a similar issue in reverse).

**Comment by william-silversmith** [comment] 2021-07-26 19:54
Hey guys, we used to default it on, but then switched it off to support "synthetic manifests" about a year ago. It's been a while so I'm trying to refresh on exactly how that subsystem works. 

https://github.com/seung-lab/cloud-volume/commit/da9ba287001fc5f8acdec4bad77e5591c2ad6300#diff-6d4001b8dd6de6d8cd3af12a2edb67ad4245df6296c6b4b0ac8bc201045ae257R146

**Comment by sdorkenw** [comment] 2021-07-26 20:45
`use_bytes_offset` should not make any difference in the result. Background on `use_byte_offsets`:

For meshes stored in shards within hybrid (sharded for the initial segmentation, unsharded for all new segments) meshing resources (FlyWire: non-sharded, FANC: hybrid, minnie: hybrid), one needs to make multiple calls to first extract the byte offset of the data and then to extract the actual data. We found that GCP incurs a lot of latency for these tiny calls. As the manifest generation already extracts this data, we included the option to have the manifest transmit the offsets - cloudvolume can choose to use them or not (--> `use_bytes_offset`).

@william-silversmith I dug into the code base and it seems that the actual mesh loading code that is run for both options (`True`, `False`) is completely separate:
`use_bytes_offset=False` calls [`get_meshes_on_bypass`](https://github.com/seung-lab/cloud-volume/blob/b6a651789891fbeb5b7ff36c644c4fa48790e622/cloudvolume/datasource/graphene/mesh/sharded.py#L208)
`use_bytes_offset=True` calls [`get_meshes_via_manifest_byte_offsets`](https://github.com/seung-lab/cloud-volume/blob/b6a651789891fbeb5b7ff36c644c4fa48790e622/cloudvolume/datasource/graphene/mesh/sharded.py#L142)

The bypass is a bit curious. `bypass=True` leads to the same function and is - I think - synonymous with "speculative manifests" which can very well miss meshes if anything in the remeshing did not go as expected. But it seems to me that the IDs going into this function are already coming from a proper manifest (?). I suspect either the entire call is basically retrieving a speculative manifest / mesh or there is something not right in `get_meshes_via_manifest_byte_offsets` function. 

Either way, I would suggest making `use_bytes_offset=True` the default as that should be better in every way. 

@ceesem Could you share the specific example?

CC: @akhileshh

**Comment by ceesem** [comment] 2021-07-26 20:46
@sdorkenw I gave a specific root id in my original post. It behaves the same way on either public or production Minnie65.

**Comment by sdorkenw** [comment] 2021-07-26 21:07
@ceesem Sorry, I missed that....

**Comment by sdorkenw** [comment] 2021-07-26 21:10
> It behaves the same way on either public or production Minnie65.

Does it do the same thing with `use_bytes_offset=[True, False]`?

**Comment by ceesem** [comment] 2021-07-26 21:11
Ah — seg id 864691134988768122 works with use_bytes_offset=True, but with the (current default) of False it is missing a large chunk around the apical bifurcation point.

**Comment by william-silversmith** [comment] 2021-07-26 22:54
Ah okay! I'm happy to switch it back. I don't precisely recall our conversations about the original switch, but I think it had to do with reducing load on the PCG servers when running large jobs?

**Comment by jefferis** [comment] 2021-07-27 00:19
Visual example of impact.
Neuroglancer:
![image](https://user-images.githubusercontent.com/23763/127075389-aaabe988-e00c-4c8a-8c25-8b8d7203aa64.png)
Cloudvolume (use_bytes_offset at default):
![image](https://user-images.githubusercontent.com/23763/127075294-66d54167-9e87-407f-b47f-018602353abf.png)

**Comment by fcollman** [comment] 2021-07-27 02:08
the use_bytes_offset is a bit of a headfake, as the underlying cause of this problem is that that code path is the only way presently to get fetch_manifest called with verify=True.  We could also fix this problem by making verify=True the default option for the non_bytes_offset call.  I think having verify=True as a kwarg on download makes the most sense to me... using the server side bytes offset calculation also makes sense, but that's a bit orthogonal.

**Comment by william-silversmith** [comment] 2021-07-27 02:11
Wouldn't `verify=True` obviate the usefulness of the speculative manifest? The server is still doing all the work.

**Comment by fcollman** [comment] 2021-07-27 14:29
Here is my summary understanding of the situation..
there are 3 different possible code paths.

1. just assuming all the meshes are in sharded format (this is what bypass=True is doing) no server involvement.
2. letting the PCG server assume that mesh fragments have been generated at all the levels it expects they will have been generated at. (this is verify=False) (this is what the default code path is doing now.. uses server, but server doesn't read from storage)
3. first having the PCG server check if a higher level stitched mesh fragment exists before returning it in the manifest, if it doesn't exist go deeper into the graph to get the sub-fragments (verify=True).  (this is what the use_bytes_offset is going down now, by not specifying verify and letting it default to verify=True.).  

Orthogonally, there is whether cloudvolume/neuroglancer has to also read the sharded index to find the offset for each ID within the shard, or whether the PCG server did it for you (with lower latency) which is what the use_bytes_offset was actually intended for.

**Comment by william-silversmith** [comment] 2021-07-27 22:03
Bypass tests both dynamic and initial meshes to see if the label exists. It was intended for people that knew their meshes would exist and wanted a performance edge by bypassing the server.

It's difficult for me to see the utility of `verify=True` without `use_byte_offsets` (it'll just be slower) so I think I'll just flip the default back to True.

**Comment by william-silversmith** [comment] 2021-07-29 20:44
Change is made in https://github.com/seung-lab/cloud-volume/commit/566d95994a9e5f543508d829c9e0779426fdfaae Will release this version in a bit.

**Comment by william-silversmith** [comment] 2021-09-07 22:37
This was released, forgot to close the issue. Thanks all!

**Closed by william-silversmith** 2021-09-07 22:37 UTC
Labels: bug, meshes, graphene
